backend:
  name: github
  repo: MihaiStu/blog-admi
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Artículos"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "paginas"
    label: "Páginas"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
